all:
	gcc ex06.c ../ft_putchar.c ../ex06/ft_print_alphabet.c -o ex06.out
	gcc ex07.c ../ft_putchar.c ../ex07/ft_print_numbers.c -o ex07.out
	gcc ex08.c ../ft_putchar.c ../ex08/ft_is_negative.c -o ex08.out
	gcc ex10.c ../ex10/ft_swap.c -o ex10.out
	gcc ex11.c ../ex11/ft_div_mod.c -o ex11.out
	gcc ex12.c ../ex12/ft_iterative_factorial.c -o ex12.out
	gcc ex13.c ../ex13/ft_recursive_factorial.c -o ex13.out
	gcc ex14.c ../ex14/ft_sqrt.c -o ex14.out
	gcc ex15.c ../ft_putchar.c ../ex15/ft_putstr.c -o ex15.out
	gcc ex16.c ../ex16/ft_strlen.c -o ex16.out
	gcc ex17.c ../ex17/ft_strcmp.c -o ex17.out
	gcc ex18.c ../ft_putchar.c ../ex18/ft_print_params.c -o ex18.out
	gcc ex19.c ../ft_putchar.c ../ex19/ft_sort_params.c -o ex19.out
	gcc ex20.c ../ex20/ft_strdup.c -o ex20.out
	gcc ex21.c ../ex21/ft_range.c -o ex21.out
	gcc ex22.c ../ex22/ft_abs.h -o ex22.out
	gcc ex23.c ../ex23/ft_point.h -o ex23.out
	gcc ex25.c ../ex25/ft_foreach.c -o ex25.out
	gcc ex26.c ../ex26/ft_count_if.c -o ex26.out
